plugins:
  - "@dotcom-tool-kit/eslint"
  - "@dotcom-tool-kit/npm"
  - "@dotcom-tool-kit/husky-npm"
  - "@dotcom-tool-kit/mocha"
  - "./toolkit/start"
  - "./toolkit/logs"
  - "@dotcom-tool-kit/backend-heroku-app"

commands:
  test:local:
    - Mocha

  test:ci:
    - Eslint

  run:local:
    - SyndicationAPITask
    - SyndicationAPILogs

options:
  tasks:
    Eslint:
      files:
        - "**/*.{js,jsx}"
    Mocha:
      configPath: "./.mocharc.json"
    HerokuProduction:
      scaling:
        ft-next-syndication-api:
          web:
            size: standard-1X
            quantity: 1
  plugins:
    "@dotcom-tool-kit/circleci":
      cimgNodeVersions: [22.12-browsers]
    "@dotcom-tool-kit/heroku":
      pipeline: "ft-next-syndication-api"
      systemCode: "next-syndication-api"
    "@dotcom-tool-kit/doppler":
      project: next-syndication-api
