plugins:
  - "@dotcom-tool-kit/eslint"
  - "@dotcom-tool-kit/secret-squirrel"
  - "@dotcom-tool-kit/npm"
  - "@dotcom-tool-kit/husky-npm"
  - "@dotcom-tool-kit/mocha"
  - "./toolkit/start"
  - "./toolkit/logs"
  - "@dotcom-tool-kit/backend-heroku-app"

hooks:
  test:local:
    - Mocha

  test:ci:
    - Eslint

  run:local:
    - SyndicationAPITask
    - SyndicationAPILogs

options:
  "@dotcom-tool-kit/mocha": {}
  "@dotcom-tool-kit/eslint": {}
  "@dotcom-tool-kit/circleci": { nodeVersion: 18.17-browsers }
  "@dotcom-tool-kit/heroku":
    pipeline: ft-next-syndication-api
    systemCode: next-syndication-api
    scaling:
      ft-next-syndication-api:
        web:
          size: standard-1X
          quantity: 1
  "@dotcom-tool-kit/doppler":
    project: next-syndication-api
