---
  BASE_URI_FT_API: http://localhost:5050

  CONTRIBUTOR_EMAIL:
    transport:
      jsonTransport: true

  CONVERT_FORMAT_COMMAND: "./test/fixtures/pandoc_stub"

  NODE_ENV: branch

  QUEUE_PURGE_THROTTLE_LIMIT_MS: 25

  THE_GOOGLE:
    AUTH_FILE_NAME: "GOOGLE_AUTH_FILE_NAME.json"
    AUTH_KEY:
      type: "GOOGLE_AUTH_TYPE"
      project_id: "GOOGLE_AUTH_PROJECT_ID"
      private_key_id: "GOOGLE_AUTH_PRIVATE_KEY_ID"
      private_key: "GOOGLE_AUTH_PRIVATE_KEY"
      client_email: "GOOGLE_AUTH_CLIENT_EMAIL"
      client_id: "GOOGLE_AUTH_CLIENT_ID"
      auth_uri: "GOOGLE_AUTH_AUTH_URI"
      token_uri: "GOOGLE_AUTH_TOKEN_URI"
      auth_provider_x509_cert_url: "GOOGLE_AUTH_AUTH_PROVIDER_X509_CERT_URL"
      client_x509_cert_url: "GOOGLE_AUTH_CLIENT_X509_CERT_URL"
