---
  AWS_ACCESS_KEY: "AWS_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY"
  SESSION_PUBLIC_KEY: "SESSION_PUBLIC_KEY"
  SYNDICATION_DOWNLOAD_SQS_URL: "SYNDICATION_DOWNLOAD_SQS_URL"
  API_KEY: "API_KEY"
  AWS_LAMBDA_TO_SPLUNK: "AWS_LAMBDA_TO_SPLUNK"
  CIRCLECI_AUTH_TOKEN: "CIRCLECI_AUTH_TOKEN"
  CIRCLECI_REBUILD_KEY: "CIRCLECI_REBUILD_KEY"
  COCO_API_AUTHORIZATION: "COCO_API_AUTHORIZATION"
  FT_COCO_API_DEV_KEY: "FT_COCO_API_DEV_KEY"
  FT_DEVELOPER_API_KEY: "FT_DEVELOPER_API_KEY"
  FT_DEVELOPER_CLIENT_NAME: "FT_DEVELOPER_CLIENT_NAME"
  FT_GRAPHITE_KEY: "FT_GRAPHITE_KEY"
  FT_NEXT_BACKEND_KEY: "FT_NEXT_BACKEND_KEY"
  FT_NEXT_BACKEND_KEY_OLD: "FT_NEXT_BACKEND_KEY_OLD"
  HEROKU_AUTH_TOKEN: "HEROKU_AUTH_TOKEN"
  HOSTEDGRAPHITE_READ_APIKEY: "HOSTEDGRAPHITE_READ_APIKEY"
  KONSTRUCTOR_API_KEY: "KONSTRUCTOR_API_KEY"
  MYFT_API_KEY: "MYFT_API_KEY"
  PERSONALISED_FEED_API_KEY: "PERSONALISED_FEED_API_KEY"
  USER_PREFS_API_KEY: "USER_PREFS_API_KEY"
  api2key: "api2key"
  apikey: "apikey"
