---
  ALS_API_KEY: "ALS_API_KEY"
  AUTH_API_CLIENT_ID: "AUTH_API_CLIENT_ID"
  AWS_ACCESS_KEY: "AWS_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY"
  API_KEY: "API_KEY"
  AWS_LAMBDA_TO_SPLUNK: "AWS_LAMBDA_TO_SPLUNK"
  CIRCLECI_AUTH_TOKEN: "CIRCLECI_AUTH_TOKEN"
  CIRCLECI_REBUILD_KEY: "CIRCLECI_REBUILD_KEY"
  COCO_API_AUTHORIZATION: "COCO_API_AUTHORIZATION"
  DB:
    database: "DATABASE_NAME"
    host: "DATABASE_HOST"
    password: "DATABASE_PASSWORD"
    port: "DATABASE_PORT"
    uri: "DATABASE_URL"
    user_name: "DATABASE_USER_NAME"
  DEFAULT_DB_ENDPOINT: "DEFAULT_DB_ENDPOINT"
  FT_COCO_API_DEV_KEY: "FT_COCO_API_DEV_KEY"
  FT_DEVELOPER_API_KEY: "FT_DEVELOPER_API_KEY"
  FT_DEVELOPER_CLIENT_NAME: "FT_DEVELOPER_CLIENT_NAME"
  FT_GRAPHITE_KEY: "FT_GRAPHITE_KEY"
  FT_NEXT_BACKEND_KEY: "FT_NEXT_BACKEND_KEY"
  FT_NEXT_BACKEND_KEY_OLD: "FT_NEXT_BACKEND_KEY_OLD"
  HEROKU_AUTH_TOKEN: "HEROKU_AUTH_TOKEN"
  HOSTEDGRAPHITE_READ_APIKEY: "HOSTEDGRAPHITE_READ_APIKEY"
  KONSTRUCTOR_API_KEY: "KONSTRUCTOR_API_KEY"
  MYFT_API_KEY: "MYFT_API_KEY"
  OVERRIDE_FLAGS_FROM_COOKIE: "OVERRIDE_FLAGS_FROM_COOKIE"
  NEW_SYNDICATION_USERS: "NEW_SYNDICATION_USERS"
  NEW_SYNDICATION_USERS_AWAITING: "NEW_SYNDICATION_USERS_AWAITING"
  NODE_ENV: "NODE_ENV"
  PERSONALISED_FEED_API_KEY: "PERSONALISED_FEED_API_KEY"
  RAVEN_URL: "RAVEN_URL"
  SESSION_API_KEY: "SESSION_API_KEY"
  SESSION_PUBLIC_KEY: "SESSION_PUBLIC_KEY"
  SPLUNK_URL: "SPLUNK_URL"
  SYNDICATION_DOWNLOAD_SQS_URL: "SYNDICATION_DOWNLOAD_SQS_URL"
  USER_PREFS_API_KEY: "USER_PREFS_API_KEY"
  api2key: "api2key"
  apikey: "apikey"
  SALESFORCE:
    CALLBACK_URI: "SALESFORCE_CALLBACK_URI"
    CLIENT_ID: "SALESFORCE_CLIENT_ID"
    CLIENT_SECRET: "SALESFORCE_CLIENT_SECRET"
    PASSWORD: "SALESFORCE_PASSWORD"
    USERNAME: "SALESFORCE_USERNAME"
  SLACK:
    INCOMING_HOOK_URL: "SLACK_INCOMING_HOOK_URL"
  THE_GOOGLE:
    AUTH_FILE_NAME: "GOOGLE_AUTH_FILE_NAME"
    AUTH_KEY:
      type: "GOOGLE_AUTH_TYPE"
      project_id: "GOOGLE_AUTH_PROJECT_ID"
      private_key_id: "GOOGLE_AUTH_PRIVATE_KEY_ID"
      private_key: "GOOGLE_AUTH_PRIVATE_KEY"
      client_email: "GOOGLE_AUTH_CLIENT_EMAIL"
      client_id: "GOOGLE_AUTH_CLIENT_ID"
      auth_uri: "GOOGLE_AUTH_AUTH_URI"
      token_uri: "GOOGLE_AUTH_TOKEN_URI"
      auth_provider_x509_cert_url: "GOOGLE_AUTH_AUTH_PROVIDER_X509_CERT_URL"
      client_x509_cert_url: "GOOGLE_AUTH_CLIENT_X509_CERT_URL"
