---
  PORT: 3255

  AWS_REGION: eu-west-1

  BASE_URI_FT_API: https://api.ft.com
  BASE_URI_PATH: /syndication

  CONVERT_FORMAT_COMMAND: pandoc

  DOWNLOAD_ARCHIVE_EXTENSION: zip
  DOWNLOAD_ARTICLE_FORMATS:
    doc: docx
    docx: docx
    htm: html
    html: html
    pdf: pdf
    plain: plain
    text: plain
    txt: plain
  DOWNLOAD_ARTICLE_EXTENSION_OVERRIDES:
    plain: txt
  DOWNLOAD_FILENAME_PREFIX: FT_

  QUEUE_PURGE_THROTTLE_LIMIT_MS: 60000

  TIMEOUT_ARTICLE_FETCH: 10000

  TEST:
    FIXTURES_DIRECTORY: ./test/fixtures
    TEMP_FILES_DIRECTORY: ./test/temp