---
  PORT: 3255

  AWS_REGION: eu-west-1

  API_KEY_HEADER_NAME: X-Api-Key

  AUTH_API_ID_PROPERTY: client_id
  AUTH_API_QUERY_LICENCE:
    redirect_uri: https://www.ft.com
    response_type: token
    scope: licence_data
  AUTH_API_QUERY_USER:
    redirect_uri: https://www.ft.com
    response_type: token
    scope: profile_min

  AUTH_SIGN_IN_REDIRECT_PROPERTY: location
  AUTH_SIGN_IN_URI: https://accounts.ft.com/login
  AUTH_SIGN_OUT_URI: https://accounts.ft.com/logout

  BASE_URI_FT_API: https://api.ft.com
  BASE_URI_PATH: /syndication

  CONVERT_FORMAT_COMMAND: pandoc

  DOWNLOAD_ARCHIVE_EXTENSION: zip
  DOWNLOAD_ARTICLE_FORMATS:
    doc: docx
    docx: docx
    htm: html
    html: html
    pdf: pdf
    plain: plain
    text: plain
    txt: plain
  DOWNLOAD_ARTICLE_EXTENSION_OVERRIDES:
    plain: txt
  DOWNLOAD_FILENAME_PREFIX: FT_

  DOWNLOAD_STATE_MAP:
    complete: true

  FEATURE_FLAGS:
    - syndication
    - syndicationNew
    - syndicationNewOverride
    - syndicationNewUsersAwaiting
    - syndicationRedux

  FORMAT_ARTICLE_CLEAN_ELEMENTS:
    - a
    - ft-concept
    - ft-content
  FORMAT_ARTICLE_STRIP_ELEMENTS:
    - ft-related
    - img
    - script
    - pull-quote

  LICENCE_ITEMS_ARRAY_PROPERTY: accessLicences

  MEDIA_RESOURCE_TYPES:
    - MediaResource
    - Podcast
    - Video

  QUEUE_PURGE_THROTTLE_LIMIT_MS: 60000

  SALESFORCE:
    API_VERSION: v34.0
    BASE_URI: SCRMContract
    ENVIRONMENT: sandbox
    CONNECTION_MODE: single
    REFRESH_CONTRACT_PERIOD: 86400000 # 24 hours in ms
    TEST_CONTRACT: FTS-14046740
    STUB_CONTRACTS:
      - CA-00001558

  SAVED_STATE_MAP:
    save: true

  SESSION_PRODUCTS_PATH: /products
  SESSION_URI: https://session-next.ft.com

  STUB_FLAGS: false

  SYNDICATION_PRODUCT_CODE: S1

  TIMEOUT_ARTICLE_FETCH: 10000

  TEST:
    SKIP_LICENCE_ID: FEATURE-FLAG-ENABLED-SYNDICATION-LICENCE
    SKIP_SYNDICATION_CONTRACT_ID: FEATURE-FLAG-ENABLED-SYNDICATION-CONTRACT-ID
    SKIP_USER_ID: FEATURE-FLAG-ENABLED-SYNDICATION-USER
    FIXTURES_DIRECTORY: ./test/fixtures
    TEMP_FILES_DIRECTORY: ./test/temp

  USER_PROFILE_DATA_PROPERTY: user
