---
  PORT: 3255

  AWS_REGION: eu-west-1

  API_KEY_HEADER_NAME: X-Api-Key

  ASSET_TYPE_TO_CONTENT_TYPE:
    FT Article: article
    Podcast: podcast
    Video: video

  ASSET_TYPE_TO_DISPLAY_TYPE:
    FT Article: Articles
    Podcast: Podcasts
    Video: Videos

  AUTH_API_ID_PROPERTY: client_id
  AUTH_API_QUERY_LICENCE:
    redirect_uri: https://www.ft.com
    response_type: token
    scope: licence_data
  AUTH_API_QUERY_USER:
    redirect_uri: https://www.ft.com
    response_type: token
    scope: profile_min

  AUTH_SIGN_IN_REDIRECT_PROPERTY: location
  AUTH_SIGN_IN_URI: https://accounts.ft.com/login
  AUTH_SIGN_OUT_URI: https://accounts.ft.com/logout

  BASE_URI_FT_API: https://api.ft.com
  BASE_URI_PATH: /syndication

  CONTENT_TYPE_ALIAS:
    content: article
    contentpackage: package
    mediaresource: video

  CONTENT_TYPE_TO_ASSET_TYPE:
    article: "FT Article"
    mediaresource: "Video"
    package: "FT Article"
    placeholder: "FT Article"
    podcast: "Podcast"
    video: "Video"

  CONVERT_FORMAT_COMMAND: pandoc

  CRON:
    content_cleanup: "* * 0 * * *"
    content_cache: "* */5 * * * *"
    migration: "* 0,15,30,45 * * * *"

  DEFAULT_DOWNLOAD_FORMAT: docx

  DOWNLOAD_ARCHIVE_EXTENSION: zip
  DOWNLOAD_ARTICLE_FORMATS:
    doc: docx
    docx: docx
    htm: html
    html: html
#    pdf: pdf
    plain: plain
    text: plain
    txt: plain
  DOWNLOAD_ARTICLE_EXTENSION_OVERRIDES:
    plain: txt
  DOWNLOAD_FILENAME_PREFIX: FT_

  DOWNLOAD_STATE_MAP:
    complete: true
    started: true

  EXPORT:
    downloads:
      content_type: Content Type
      title: Item
      content_url: URL
      download_format: Download Format
      user_email: User
      published_date: Publication Date
      time: Downloaded Date
    saved_items:
      content_type: Content Type
      title: Item
      content_url: URL
      user_email: User
      published_date: Publication Date
      time: Saved Date

  FEATURE_FLAGS:
    - syndication
    - syndicationDownloadMediaResource
    - syndicationNew
    - syndicationNewOverride
    - syndicationNewUsersAwaiting
    - syndicationPlatform
    - syndicationRedux

  FORMAT_ARTICLE_CLEAN_ELEMENTS:
    - a
    - ft-concept
    - ft-content
  FORMAT_ARTICLE_STRIP_ELEMENTS:
    - ft-related
    - img
    - script
    - pull-quote

  JS_TO_DB_TYPES:
    default: S
    array: L
    boolean: BOOL
    number: N
    object: M
    string: S

  LICENCE_ITEMS_ARRAY_PROPERTY: accessLicences

  MEDIA_RESOURCE_TYPES:
    - MediaResource
    - Podcast
    - Video

  MESSAGES:
    MSG_2000: >
      <p>Please ensure you have considered your <a data-trackable="contractual-rights" href="/republishing/contract">contractual rights</a> before republishing</p>
    MSG_2100: >
      <p>This content has already been downloaded and therefore will not count towards your republishing limit.</p>
      <p>Please ensure you have considered your <a data-trackable="contractual-rights" href="/republishing/contract">contractual rights</a> before republishing</p>
    MSG_2200: >
      <p>Please contact us for details of republishing rights for this content (<a href="mailto:syndication@ft.com">syndication@ft.com</a> or +44 (0)207 873 4816).</p>
    MSG_2300: >
      <p>This content will incur additional charges to republish. Please contact us for further details (<a href="mailto:syndication@ft.com">syndication@ft.com</a> or +44 (0)207 873 4816).</p>
    MSG_2320: >
      <p>This content will incur additional charges to republish. Please contact us for further details (<a href="mailto:syndication@ft.com">syndication@ft.com</a> or +44 (0)207 873 4816).</p>
      <p>Please ensure you have considered your <a data-trackable="contractual-rights" href="/republishing/contract">contractual rights</a> before republishing</p>
    MSG_2340: >
      <p>This content has already been downloaded and therefore will not count towards your republishing limit.</p>
      <p>This content will incur additional charges to republish. Please contact us for further details (<a href="mailto:syndication@ft.com">syndication@ft.com</a> or +44 (0)207 873 4816).</p>
      <p>Please ensure you have considered your <a data-trackable="contractual-rights" href="/republishing/contract">contractual rights</a> before republishing</p>
    MSG_4000: >
      <p>This content is not available for republishing.</p>
    MSG_4100: >
      <p>You have reached your download limit for articles. Please contact your Account Manager to increase your limit.</p>
    MSG_4200: >
      <p>Your contract does not allow {{type}}s to be downloaded. Please contact your Account Manager to change this.</p>
    MSG_5000: >
      <p>Sorry, an error has occurred. Please try signing out and then in again. If error persists, please contact your Account Manager.</p>

  NODE_ENV: development

  QUEUE_PURGE_THROTTLE_LIMIT_MS: 60000

  SALESFORCE:
    API_VERSION: v34.0
    BASE_URI: SCRMContract
    ENVIRONMENT: production
    CONNECTION_MODE: single
    CRON_CONFIG:
      MAX_CALLS: 2
      MAX_TIME_PER_CALL: 900000
    REFRESH_CONTRACT_PERIOD: 86400000 # 24 hours in ms
    TEST_CONTRACT: FTS-14046740
    STUB_CONTRACTS:
      - CA-00001558

  SAVED_STATE_MAP:
    saved: true

  SESSION_PRODUCTS_PATH: /products
  SESSION_URI: https://session-next.ft.com

  SPREADSHEET_MAPPINGS:
    contracts:
      licenceename: licencee_name
      contractid: contract_id
      contenttype: content_type
      legacydownloadcount: legacy_download_count
      lastupdated: last_updated
    users:
      licenceename: licencee_name
      contractid: contract_id
      userid: user_id
      lastupdated: last_updated

  STUB_FLAGS: false

  SYNDICATION_PRODUCT_CODE: S1

  TIMEOUT_ARTICLE_FETCH: 10000

  TEST:
    SKIP_LICENCE_ID: FEATURE-FLAG-ENABLED-SYNDICATION-LICENCE
    SKIP_SYNDICATION_CONTRACT_ID: FEATURE-FLAG-ENABLED-SYNDICATION-CONTRACT-ID
    SKIP_USER_ID: FEATURE-FLAG-ENABLED-SYNDICATION-USER
    FIXTURES_DIRECTORY: ./test/fixtures
    TEMP_FILES_DIRECTORY: ./test/temp

  TRACKING:
    DATA:
      category: syndication
      context:
        app: Syndication
        edition: uk
        product: next
      device:
        spoor_session_is_new: true
      system:
        api_key: qUb9maKfKbtpRsdp0p2J7uWxRPGJEP
        product: Syndication
    HEADERS:
      accept: application/json
      content-type: application/json
    METHOD: POST
    URI: https://spoor-api.ft.com/ingest

  USER_PROFILE_DATA_PROPERTY: user
